import type { AuthRouteDefinition } from "../types/auth.http.types.js";

export const authRoutes: AuthRouteDefinition[] = [
  {
    method: "GET",
    path: "/auth/bootstrap/status",
    handler: "bootstrapStatus",
    requiresAuth: false,
    requiresCsrf: false,
  },
  {
    method: "POST",
    path: "/auth/bootstrap",
    handler: "bootstrap",
    requiresAuth: false,
    requiresCsrf: false,
  },
  {
    method: "POST",
    path: "/auth/login",
    handler: "login",
    requiresAuth: false,
    requiresCsrf: false,
  },
  {
    method: "POST",
    path: "/auth/refresh",
    handler: "refresh",
    requiresAuth: false,
    requiresCsrf: true,
  },
  {
    method: "POST",
    path: "/auth/logout",
    handler: "logout",
    requiresAuth: false,
    requiresCsrf: true,
  },
  {
    method: "GET",
    path: "/auth/session",
    handler: "currentSession",
    requiresAuth: true,
    requiresCsrf: false,
  },
  {
    method: "POST",
    path: "/auth/recovery/request",
    handler: "requestPasswordRecovery",
    requiresAuth: false,
    requiresCsrf: false,
  },
  {
    method: "POST",
    path: "/auth/recovery/verify",
    handler: "verifyPasswordRecovery",
    requiresAuth: false,
    requiresCsrf: false,
  },
  {
    method: "POST",
    path: "/auth/recovery/reset",
    handler: "resetPassword",
    requiresAuth: false,
    requiresCsrf: false,
  },
  {
    method: "POST",
    path: "/auth/otp/sensitive-action",
    handler: "requestSensitiveActionOtp",
    requiresAuth: true,
    requiresCsrf: true,
  },
  {
    method: "POST",
    path: "/auth/otp/sensitive-action/verify",
    handler: "verifySensitiveActionOtp",
    requiresAuth: true,
    requiresCsrf: true,
  },
];
